spring:
  application:
    name: sentimentum-backend
  datasource:
    url: jdbc:h2:mem:sentimentum;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

server:
  port: 8080

youtube:
  api-key: ${YOUTUBE_API_KEY:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
